http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
    kc-sec:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: no-referrer-when-downgrade
        customFrameOptionsValue: SAMEORIGIN